### PR TITLE
Screen Polish

### PR DESCRIPTION
**Pull request by Moutasim02**
- Restyled the whole UI with Bootstrap.
- Adapt the code to standard.
- Removed unnecessary dependencies.

### CODE REVIEW

**Comment by binHarby** [comment]
just a friendly reminder to remember to pull from master on this branch, its behind

**Comment by Moutasim02** [comment]
> git pull --tags origin master
From https://github.com/SpecialProjectADU/Site
 * branch            master     -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.


@binHarby I think I need help

**Comment by Moutasim02** [comment]
Fixed!

**Review by binHarby — APPROVED** [review]
Looks good

**Pull request merged**
