### PR TITLE
Attempt to fix #53 & #57

### LINKED ISSUE #53: Main Page Sticky Navbar
navBarLooksWrong

Mid page logic needs to be fixed.  Nothing in the Navbar shows when scrolling over, due to the font color and the transparent background. Maybe fix the nav bar after scrolling to be similar to his?

navbar2

### PR DESCRIPTION
**Pull request by AlyafeiAli**
Attempt to fix #53 & #57

### CODE REVIEW

**Comment by binHarby** [comment]
defer works on the tags loaded it before it. Move the tag to under the 


comment also

**Comment by binHarby** [comment]
I just did that no worries

**Comment by binHarby** [comment]
just sync it with master

**Comment by AlyafeiAli** [comment]
Good job

**Comment by binHarby** [comment]
wait why you close the pr lol, I made the commit, it still needs syncing

**Comment by binHarby** [comment]
Wait I'll do it, give me a sec

**Comment by AlyafeiAli** [comment]
My bad lol

**Review by binHarby — APPROVED** [review]
Great @AlyafeiAli

**Pull request merged**
